- name: catalogue
  hosts: catalogue
  become: yes
  tasks:
  - name: disable old nodejs and enable nodejs
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

  - name: install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present

  - name: create roboshop user
    ansible.builtin.user:
      name: roboshop

  - name: recursively remove app directory
    ansible.builtin.file:
      path: /app
      state: absent    

  - name: creating app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: download catalogue application file to app directory
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /tmp 

  - name: unzip the catalogue.zip file
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes

  - name: install the dependencies
    ansible.builtin.command: npm install
    args:
      chdir: /app

  - name: copy the systemd catalogue service
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service

  - name: daemon-reload and start
    ansible.builtin.systemd_service:
      daemon_reload: true
  
  # lets start after the data is load

  - name: copy mongodb.repo
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: install mongodb clinet
    ansible.builtin.package:
      name: mongodb-org-shell
      state: present 

  - name: get the categories proudct count
    ansible.builtin.command: mongo --host mongodb.gopisri.cloud --quiet --eval 'db = db.getSiblingDB("catalogue"); db.products.count()'
    register: product_count

  # - name: print the count
  #   ansible.builtin.debug:
  #     msg: "product_count: {{product_count}}"

  - name: load catalogue data
    ansible.builtin.command: mongo --host mongodb.gopisri.cloud < /app/schema/catalogue.js
    when: product_count.stdout == "0" # keep in double quotes

  - name: start and enable catalogue
    ansible.builtin.service:
      name: catalogue
      state: restarted
      enabled: yes               
   
  


